version: "3.9"
services:
  typesense:
    image: typesense/typesense:0.25.1
    container_name: ts
    ports:
      - "8108:8108"
    volumes:
      - ./data/typesense:/data
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: ${TS_API_KEY:-changeMe}
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - appnet

  ui:
    build:
      context: .
      dockerfile: shared/ui/Dockerfile
    container_name: ui
    ports:
      - "8501:8501"
    volumes:
      - ./shared:/app/shared
    environment:
      TS_URI: http://typesense:8108
      TS_KEY: ${TS_API_KEY:-changeMe}
    depends_on:
      - typesense
      - redis
    networks:
      - appnet
    command: streamlit run shared/ui/st_app.py --server.port 8501 --server.address 0.0.0.0

networks:
  appnet:
    driver: bridge
